# Generated by Django 3.2.3 on 2021-10-12 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategori',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kate', models.CharField(default='', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Makan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(default='', max_length=10)),
                ('ktgori', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kategori', to='makanan.kategori')),
            ],
        ),
    ]
