# Generated by Django 3.2.3 on 2021-10-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nopol', models.TextField(default='', max_length=10)),
                ('notempat', models.TextField(default='', max_length=5)),
                ('dtg', models.TimeField()),
                ('klr', models.TimeField()),
            ],
        ),
    ]
