# Generated by Django 3.2.3 on 2021-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='item',
            field=models.TextField(default=''),
        ),
    ]
